recipe: default.v1

language: en

pipeline:
  - name: SpacyNLP
    model: en_core_web_md
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    entity_recognition: true
    epochs: 100
    constrain_similarities: true
       # text will be processed with case-insensitive as default
    case_sensitive: false
  - name: FallbackClassifier
    threshold: 0.5
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true


policies:
  - name: TEDPolicy
    max_history: 8
    epochs: 100
    constrain_similarities: true
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: RulePolicy
       # let's handle low confidence actions
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true
assistant_id: 20240822-000840-few-graph
